---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main-copy"
      # Specify the branches to scan here
#  - package-ecosystem: npm
#    directory: "/javascript"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: bundler
#    directory: "/ruby"
#    schedule:
#      interval: "weekly"
